version: '3.8'

# Docker connection string: postgres://postgres:postgres@localhost:5430/

services:
  db:
    image: postgres
    container_name: bookmark-it-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medium_clone
      POSTGRES_INITDB_ARGS: '-A md5'
    volumes:
      - medium_db:/var/lib/postgresql/data
    ports:
      - '5430:5430'

volumes:
  medium_db: