version: '3.8'

# Docker connection string: postgres://postgres:postgres@localhost:5430/

services:
  db:
    image: postgres
    container_name: bookmark-it-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmark_it
      POSTGRES_INITDB_ARGS: '-A md5'
    volumes:
      - bookmarkIT_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  bookmarkIT_db: